const { chromium } = require('C:/Users/Qazim/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs');
const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist','--enable-unsafe-swiftshader']});
 const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'});
 await page.waitForFunction(()=>window.clubGilmore?.ready,{timeout:60000});
 await page.screenshot({path:'evidence/desktop.png',fullPage:true});
 const stats=await page.evaluate(()=>{const c=window.clubGilmore;let meshes=0,vertices=0; c.model.root.traverse(o=>{if(o.isMesh){meshes++;vertices+=o.geometry.attributes.position.count;}});return {rooms:c.rooms.length,meshes,vertices,drawCalls:c.renderer.info.render.calls,triangles:c.renderer.info.render.triangles,modelBounds:c.model.bounds.getSize(c.camera.position.clone()).toArray(),scrollWidth:document.documentElement.scrollWidth,clientWidth:innerWidth};});
 await page.getByRole('button',{name:'Indoor pool & hydrotherapy',exact:true}).click();
 await page.waitForTimeout(850);await page.screenshot({path:'evidence/pool.png',fullPage:true});
 await page.getByRole('button',{name:'Back to the whole floor'}).click();await page.waitForTimeout(850);
 await page.getByRole('button',{name:'Plan view',exact:true}).click();await page.waitForTimeout(850);await page.screenshot({path:'evidence/plan.png',fullPage:true});
 const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});
 await mobile.goto('http://127.0.0.1:4173/',{waitUntil:'networkidle'});await mobile.waitForFunction(()=>window.clubGilmore?.ready);await mobile.screenshot({path:'evidence/mobile.png',fullPage:true});
 await mobile.getByRole('button',{name:'Find a space',exact:true}).click();await mobile.getByRole('searchbox').fill('Main gym');await mobile.getByRole('button',{name:'Main gym',exact:true}).click();await mobile.waitForTimeout(850);await mobile.screenshot({path:'evidence/mobile-detail.png',fullPage:true});
 fs.writeFileSync('evidence/first-inspection.json',JSON.stringify({errors,stats},null,2));console.log(JSON.stringify({errors,stats}));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
